// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPPkkeuFcSLHArxulivyli-5Nqyx4sy4w',
    appId: '1:336199999486:web:90fcc9be3c69dc8f3daaaf',
    messagingSenderId: '336199999486',
    projectId: 'fir-61fc0',
    authDomain: 'fir-61fc0.firebaseapp.com',
    databaseURL: 'https://fir-61fc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-61fc0.appspot.com',
    measurementId: 'G-2BJETY3M7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXi9KI3uZcq6tztUcdpj3w-JbzSEzPT94',
    appId: '1:336199999486:android:8ec426037ffe8d6f3daaaf',
    messagingSenderId: '336199999486',
    projectId: 'fir-61fc0',
    databaseURL: 'https://fir-61fc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-61fc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoozG4XWQYty9Q2v08GMYe6O5ig1sRw9s',
    appId: '1:336199999486:ios:240cd738453169ea3daaaf',
    messagingSenderId: '336199999486',
    projectId: 'fir-61fc0',
    databaseURL: 'https://fir-61fc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-61fc0.appspot.com',
    iosClientId: '336199999486-oo7fv0nbrg5ipu6qc23tfno8v53op3g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.climateaction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoozG4XWQYty9Q2v08GMYe6O5ig1sRw9s',
    appId: '1:336199999486:ios:240cd738453169ea3daaaf',
    messagingSenderId: '336199999486',
    projectId: 'fir-61fc0',
    databaseURL: 'https://fir-61fc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-61fc0.appspot.com',
    iosClientId: '336199999486-oo7fv0nbrg5ipu6qc23tfno8v53op3g2.apps.googleusercontent.com',
    iosBundleId: 'com.example.climateaction',
  );
}
